### ISSUE TITLE
Missing Sourcecode

### ISSUE THREAD

**Issue by mqus** [mathdoku/mathdoku#17]
This Project is licensed under gpl but i can't find the sourcecode for hacking on itmyself. Please make it available, as promised on your webpage.

**Comment by mathdoku** [comment]
You're right, I should have done that years ago. Well I have done it now.

Important notice: It has been several years since I have worked on this code. Also my git skills were not very well developed at that time. As far as I can remember the branch 595 should be the code that reflects the app as it is currently published on the Google Playstore. Most likely the master branch will not work succesfully and/or contain a lot of bugs (I know that I was halfway between some big refactoring but I can not recall the status).

**Comment by mqus** [comment]
Thank you very much!
